import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#002525] text-[#f5efed]">
      <body className={clsx(urbanist.className, "relative min-h-screen")}>
        {children}
      </body>
    </html>
  );
}
